### ISSUE TITLE
feat: incorporate `dev` into `supergraph` option

### ISSUE THREAD

**Issue by jjangga0214** [graphql-hive/gateway#154]
Let's say I want to build a supergraph from local servers.

Then first, I have to run this.

```sh
hive dev \
     --service foo --url http://localhost:8081 \
     --service bar --url http://localhost:8082
```

This generates *`supergraph.graphql`*.

After that, I should run this.

```sh
hive-gateway supergraph
```

This workflow is a bit cumbersome.
What if we incorporate the dev feature into `hive-gateway`?
For example,

```sh
hive-gateway supergraph \
             --dev \ # dev mode(if the flag is needed) 
             --watch \ # keep watching subgraph change
             --service foo --url http://localhost:8081 \
             --service bar --url http://localhost:8082 
```

**Comment by enisdenjo** [comment]
Hive Console and Hive Gateway are two different products. At the moment we dont plan on joining the into one.
