### ISSUE TITLE
Memory spikes when using plugins with `@graphql-hive/gateway@^1.0.8`

### ISSUE THREAD

**Issue by jaffemd** [graphql-hive/gateway#2]
We recently upgraded from `graphql-mesh` v0 to `@graphql-mesh/compose-cli` v1 + Hive Gateway as recommended by the migration guide. 

Here are our relevant dependencies and versions:
```
"dependencies": {
    "@envelop/core": "^5.0.1",
    "@graphql-hive/gateway": "^1.0.8",
    "@graphql-mesh/compose-cli": "^1.0.2",
    "@graphql-mesh/supergraph": "^0.8.6",
    "graphql": "^16.8.1",
    "graphql-yoga": "^5.6.0",
  },
```

Here's our config:
```
import { defineConfig } from "@graphql-hive/gateway";
import plugins from "@app/plugins/init";

export const gatewayConfig = defineConfig({
  supergraph: "supergraph.graphql",
  port: 8000,
  plugins: () => [...plugins],
  executionCancellation: true,
  upstreamCancellation: true,
  pollingInterval: oneYearInMs,
});
```

Before V1, memory usage was a plateau and stable. After upgrading to use hive gateway, we immediately observed unstable memory utilization. 

![image-20241014-135005](https://github.com/user-attachments/assets/bf65beb2-d1ff-4413-9530-9711247b25de)

Zooming in, every 15 to 30 minutes, there is a sharp spike in memory. 

![image-20241014-134758](https://github.com/user-attachments/assets/3b65d767-8269-4cd6-b1cd-b5988c2c2cfd)

Our only clue was [this release note in mesh v0.98.7](https://github.com/ardatan/graphql-mesh/blob/master/packages/plugins/hive/CHANGELOG.md#0987) that referenced memory leaks from plugins.

We're using a mix of homegrown plugins that perform various functions such as datadog tracing and graphql-armor vendor plugins. We ran a short experiment to turn them all off and didn't observe any memory spikes:
<img width="1384" alt="Screenshot 2024-10-16 at 10 30 50 AM" src="https://github.com/user-attachments/assets/e58df9d3-6419-4404-bede-e30f581fe079">

To isolate against the possibility of the content of our plugins being the issue, we created a barebones empty plugin to see if we still saw a memory spike just with that, and we did. Using the below config, with just a plugin that hooks into `onFetch` and `onExecute`, we still saw a memory spike after around 20 minutes. 

```
export const gatewayConfig = defineConfig({
  supergraph: "supergraph.graphql",
  port: 8000,
  plugins: () => [
    {
      onFetch: () => {},
      onExecute: () => {},
    }
  ],
  executionCancellation: true,
  upstreamCancellation: true,
  pollingInterval: oneYearInMs,
});
```

<img width="1029" alt="Screenshot 2024-10-16 at 10 31 43 AM" src="https://github.com/user-attachments/assets/62d8f274-f2b8-42e3-bd29-4ec12dbf7481">

This made it seem clear to us that there must be some memory leakage going on within the plugin infrastructure that could be similar to the issue referenced in the graphql-mesh release notes.

**Comment by enisdenjo** [comment]
> We're running the gateway on a docker container in a kubernetes pod. The docker container is running node 20.14.0.

We had some fights with Node and memory spikes in the past. Am wondering whether that's the case here too? Can we start by updating the Node in the container to the upcoming LTS ([starting tomorrow](https://endoflife.date/nodejs)) v22.10.0?

> It's overall constant, but we do get generally lower traffic overnight. The spikes are consistently every 15-20 minutes, but not exactly.

Spikes are also during lower traffic?

**Comment by jaffemd** [comment]
Upgrading node to `22.10.0` fixed our issue. Thank you!
