### ISSUE TITLE
Using @graphql-tools/executor-http with CloudflareWorkers causes error

### ISSUE THREAD

**Issue by Karibash** [graphql-hive/gateway#228]
## Description

After upgrading `@graphql-tools/executor-http` to version v1.1.10, we encountered the following error when running on Cloudflare Workers:

```
Cannot perform I/O on behalf of a different request. I/O objects (such as streams, request/response bodies, and others) created in the context of one request handler cannot be accessed from a different request's handler. This is a limitation of Cloudflare Workers which allows us to improve overall performance. (I/O type: RefcountedCanceler)
```

This issue does not occur with version v1.1.9 or earlier.

## Impact

The error appears to be related to the way I/O is handled, and several improvements made in version v1.1.10 may have a significant impact on applications deployed in the Cloudflare Workers environment.

## Steps to Reproduce

1. Deploy a Cloudflare Worker using `@graphql-tools/executor-http` at v1.1.10.
2. Execute a request that invokes the library.
3. Observe the error output as shown above.

## Expected Behavior

The worker should perform I/O operations without encountering the aforementioned error, similar to the behavior experienced with v1.1.9 or earlier.

## Additional Context

It appears that some changes between v1.1.9 and v1.1.10 might be responsible for this behavior. If there were updates related to I/O handling or request contexts, they could be contributing to the issue observed on Cloudflare Workers.

#180 #199

## Environment

- Cloudflare Workers
- @graphql-tools/executor-http v1.1.10

**Comment by ardatan** [comment]
Could you share a reproduction in code please?

**Comment by ardatan** [comment]
Closing the issue due to the lack of response.
Feel free to share a reproduction then we can reopen the issue.
