### ISSUE TITLE
Is it possible to set a request timeout on the server?

### ISSUE THREAD

**Issue by jaffemd** [graphql-hive/gateway#251]
We have the hive gateway set up in the supergraph configuration reading from a static `supergraph.graphql` file. It does not appear like there's an option currently to do this, looking through the gateway server code, it looks like the `requestTimeout` option would need to be passed in [here](https://github.com/graphql-hive/gateway/blob/32cf70583ea6469b56151e0e3f30e566e4e642d9/packages/gateway/src/servers/nodeHttp.ts#L67). 

Our current workaround is to set the timeout on the [graphql datasources directly on the supergraph schema](https://the-guild.dev/graphql/mesh/docs/handlers/graphql#fetch-strategies-and-multiple-http-endpoints-for-the-same-source). However, ideally we'd like to be able to set an overall request timeout on the server itself rather than relying on the fetch resolution timeouts to subgraphs.

**Comment by ardatan** [comment]
https://github.com/graphql-hive/gateway/pull/254
Is this what you needed?
