### ISSUE TITLE
Question: Custom logger

### ISSUE THREAD

**Issue by fauna5** [graphql-hive/gateway#3]
Hi, I need to log in JSON format so i've created a custom logger but am having some issues

```
export const gatewayConfig = defineConfig({
  ...
  logging: createJsonLogger("customLogger"),
  ...
});
```

### 1. Still some plain log lines

This works as expected but i still get some plain log lines as they don't seem to use the logger interface.

```
[2024-09-24T12:39:25.492Z] INFO   Loaded config
[2024-09-24T12:39:26.474Z] INFO  Worker graphql-hive/platform#2 Serving supergraph from config
[2024-09-24T12:39:26.477Z] INFO  Worker graphql-hive/platform#1 Serving supergraph from config
[2024-09-24T12:39:26.485Z] INFO  Worker graphql-hive/platform#2 Listening on http://localhost:4000
[2024-09-24T12:39:26.488Z] INFO  Worker graphql-hive/platform#1 Listening on http://localhost:4000
```

### 2. Worker thread
I like the worker id (`Worker graphql-hive/platform#2` above) and i would like to log it in my custom logger. But worker id is not in the context object AFAICS. Is there a way i can access it in my `GatewayPlugin`?

gateway v1.0.4

**Comment by ardatan** [comment]
> This works as expected but i still get some plain log lines as they don't seem to use the logger interface.

What do you mean by plain log lines? Can you explain it a bit more? What do you expect, and what do you get instead?

> Is there a way i can access it in my GatewayPlugin?

It is not part of the runtime. It is CLI that creates workers. We get those IDs from `process.worker.id`. So you can use the same.

**Comment by ardatan** [comment]
Closing the issue due to the lack of response. Feel free to keep us updated, we can reopen the issue later.
