### ISSUE TITLE
Self-hosted usage reporting not working

### ISSUE THREAD

**Issue by jlambynz** [graphql-hive/gateway#310]
When running the gateway using `supergraph`, adding configuration to support usage reporting to a self hosted instance, Hive is still trying to use the cloud endpoint.

Given a config something like:
```
export const gatewayConfig = defineConfig({
  supergraph: {
    type: "hive",
    endpoint: "https://self-hosted.com/artifacts/..."
    key: 123
  },
  reporting: {
    type: "hive",
    token: "123",
    selfHosting: {
      applicationUrl: "https://self-hosted.com",
      graphqlEndpoint: "https://self-hosted.com/graphql",
      usageEndpoint: "https://self-hosted.com/usage",
    },
  },
```

The gateway doesn't use the `reporting.selfHosting` options and defaults to targeting `https://app.graphql-hive.com/graphql`:
![image](https://github.com/user-attachments/assets/e19f501c-d8ba-48d3-8b15-b85f0b84e0fe)

From what I can tell, `reporting` configuration is never passed and instead a basic reporting object is constructed only consisting of `type` and `token`: https://github.com/graphql-hive/gateway/blob/main/packages/gateway/src/commands/supergraph.ts#L157-L164

I notice in the [documentation ](https://the-guild.dev/graphql/hive/docs/self-hosting/get-started) it mentions not all functionality is available in the self-hosted version, including `usage-estimation`, but it's not clear to me if that includes usage reporting in general. Should this configuration work for the self hosting?

**Comment by jlambynz** [comment]
@ardatan Not immediately confident I can easily create a reproduction but I'll review what you put together and see if that gleans any more information

In the interim, just to clarify as it seems I may have caused confusion, I'm not having any issues passing the token, it's about specifying a usage endpoint that isn't the default `https://app.graphql-hive.com/graphql`. In the config I specify `selfHosting.usageEndpoint` to point to our hosted instance, but the Hive CLI continues to try send usage to `https://app.graphql-hive.com/graphql`.

The link to the code I was referencing was me wondering if the `selfHosting` section of the config should be provided there? I did a test run locally where I changed that part of the code to

```
if (hiveRegistryToken) {
        ctx.log.info(`Configuring Hive registry reporting`);
        registryConfig = {
          reporting: {
            type: 'hive',
            token: hiveRegistryToken,
            ...loadedConfig.reporting // <----- added this line
          },
        };
      }
```

With this change, the Hive CLI started sending usage reports to our hosted instance

**Comment by ardatan** [comment]
That part of code handles the token given in the CLI arguments not from the config as in your example.
So you pass the token from CLI arguments, right?

**Comment by jlambynz** [comment]
@ardatan I wasn't, no. I did a quick test including the token as a CLI argument, but that doesn't seem to influence the endpoint it tries to send usage to

If it's useful, my setup is very bare bones:

**Dockerfile**
```
FROM ghcr.io/graphql-hive/gateway:1.6.6
COPY ./gateway.config.ts .
CMD ["supergraph",  "--host", "0.0.0.0"]
```

**gateway.config.ts**
```
import { createRemoteJwksSigningKeyProvider, defineConfig, extractFromHeader } from "@graphql-hive/gateway";
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-http";
import { BatchSpanProcessor } from "@opentelemetry/sdk-trace-base";

export const gatewayConfig = defineConfig({
  supergraph: {
    type: "hive",
    endpoint: <CDN_URL>,
    key: <CDN_KEY>,
  },
  reporting: {
    type: "hive",
    token: "<REGITRY_TOKEN>",
    selfHosting: {
      applicationUrl: "<SELF_HOSTED_URL>",
      graphqlEndpoint: "<SELF_HOSTED_URL>/graphql",
      usageEndpoint: "<SELF_HOSTED_URL>/usage",
    },
    usage: {
      clientInfo: {
        name: "gateway",
        version: "1.0.0",
      }
    }
  },
});
```
_Values enclosed in <> omitted_

**Outcome:**
![image](https://github.com/user-attachments/assets/b8a9b37b-e024-4d0d-b601-0672e99b2122)

**Expected:**
Request to be sent to `reporting.selfHosting.usageEndpoint`, not `https://app.graphql-hive.come/graphql`

**Comment by ardatan** [comment]
```ts
if (hiveRegistryToken) {
        ctx.log.info(`Configuring Hive registry reporting`);
        registryConfig = {
          reporting: {
            type: 'hive',
            token: hiveRegistryToken,
            ...loadedConfig.reporting // <----- added this line
          },
        };
      }
 ```

I reproduced your issue when I passed the token as a CLI argument which that code part only runs in this case, otherwise that code never runs. I couldn't reproduce the issue when all parameters are given in the configuration file.

Maybe I am missing something but could you try with the alphas here?
https://github.com/graphql-hive/gateway/pull/342

**Comment by jlambynz** [comment]
@ardatan Shit, sorry, I missed a crucial piece of detail which is I'm passing `HIVE_REGISTRY_TOKEN` as an environment variable rather than CLI argument. Removing this makes it work since, as you mention, it skips that piece of code.

I also tested your alpha build including `HIVE_REGISTRY_TOKEN` and it works

**Comment by ardatan** [comment]
Available in the latest release! Thanks for the feedback!
