### ISSUE TITLE
Running gateway as a proxy errors, as `@graphql-mesh/transport-http` is nissing

### ISSUE THREAD

**Issue by gilgardosh** [graphql-hive/gateway#94]
Reproduce:
Basically follow the current documentation, run as a proxy, and try opening GraphiQL.

1. Setup Hive-GW with basic config, e.g:
```
export const gatewayConfig = defineConfig({
  proxy: {
    endpoint: "http://localhost:4001/graphql",
  },
});
```

2. run the gateway
```
hive-gateway supergraph \
  http://cdn.graphql-hive.com/artifacts/v1/12713322-4f6a-459b-9d7c-8aa3cf039c2e/supergraph \
  --hive-cdn-key "YOUR HIVE CDN KEY"
  ```
  
3. Try opening GraphiQL (usually `http://localhost:4000/graphql`)
4. Get the error `Failed to introspect schema Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@graphql-mesh/transport-http' imported from /project/node_modules/@graphql-mesh/fusion-runtime/esm/utils.js`

**Comment by enisdenjo** [comment]
Fixed in one of the latest releases.
